services:
  datasetexplorationapp:
  #   profiles: ["all", "api"]
    container_name: datasetexplorationapp
    image: justadvancetechnology/datasetexploration_v1
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 2 
        cpu: 75
      resources:
        limits:
          cpus: '1'
          memory: 2Gb
    ports:
    # - 8501:8501
    - target: 8501
      x-aws-protocol: http
    healthcheck:
      test: "curl -f http://127.0.0.1:8501/_stcore/health || exit 1"
      interval: "5m"
      timeout: "5s"
      start_period: "10s"
      retries: 3
    